# Generated by Django 3.2 on 2022-06-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('error', 'エラー解決'), ('meaning', '意味理解')], max_length=100)),
                ('technique', models.CharField(max_length=50)),
                ('error_message', models.CharField(max_length=100)),
                ('error_detail', models.CharField(max_length=250)),
                ('Feature', models.CharField(max_length=100)),
            ],
        ),
    ]
