# Generated by Django 3.2 on 2022-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('rails', 'Ruby on Rails'), ('django', 'Django')], max_length=30)),
                ('error_message', models.CharField(max_length=100)),
                ('error_detail', models.CharField(max_length=250)),
                ('Feature', models.CharField(max_length=100)),
            ],
        ),
    ]
