# Generated by Django 3.2 on 2022-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchword',
            name='error_detail',
            field=models.TextField(max_length=1000),
        ),
    ]
