# Generated by Django 3.2 on 2022-08-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_word', '0002_alter_searchword_error_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchword',
            name='error_detail',
        ),
        migrations.AlterField(
            model_name='searchword',
            name='error_message',
            field=models.TextField(max_length=1000),
        ),
    ]
